stripe_config:
  N_RUs: 42
  N_stripes: 1
  space_between_RUs: 0.5
  space_between_stripes: 0.5
  stripe_start_pos:
  - 2.0
  - 2.5
  - 3.5
component_config:
  amplifier:
    gain: 1.0
    max_out_amp: 0.3
    noise_var: 0.0
    smoothness: 0.0
    mode: poly3
  fiber:
    model: PMF/with_tape/1m_taped.csv
  coupler:
    model: coupler/with_balun.s2p
waveform_config:
  waveform_type: cp-ofdm
  n_ofdm_symbols: 2
  qam_order: 4
  oversampling_factor: 4
  cp_length: 128
  pilot_spacing: 16
  pilot_symbol_re: 1
  pilot_symbol_imag: 0
  pilot_mode: block
room:
  x: 10
  y: 25
  z: 5.45
radio_stripes:
- - central_unit:
      x: 2.0
      y: 2.0
      z: 3.5
  - radio_unit:
      x: 2.0
      y: 2.5
      z: 3.5
  - radio_unit:
      x: 2.0
      y: 3.0
      z: 3.5
  - radio_unit:
      x: 2.0
      y: 3.5
      z: 3.5
  - radio_unit:
      x: 2.0
      y: 4.0
      z: 3.5
  - radio_unit:
      x: 2.0
      y: 4.5
      z: 3.5
  - radio_unit:
      x: 2.0
      y: 5.0
      z: 3.5
ue_positions:
- x: 5.0
  y: 5.0
  z: 0.0
sub_thz:
  fc: 157750000000.0
  bw: 12500000000.0
  num_subcarriers: 1024
sub10GHz:
  fc: 3500000000.0
  bw: 20000000.0
  num_subcarriers: 1024
  num_APs: 4
  ap_pos_ceil_1:
  - 5.25
  - 7.25
  - 3.5
  ap_pos_ceil_2:
  - 5.25
  - 18.25
  - 3.5
  ap_pos_wall_1:
  - 2
  - 13
  - 2.5
  ap_pos_wall_2:
  - 5.25
  - 23.5
  - 2.5
antenna:
  N_antennas_per_axis: 2
  pattern: iso
  polarization: cross
central_unit_fiber_length: 0.5
